### PR TITLE
deps: update to golang 1.18, kubernetes 1.24

### PR DESCRIPTION
**Pull request by ffromani**
We used to depend on pretty old kube and old golang. Bump both to the the a very recent - but not the newest just yet versions.
The new deps to kube 1.24 will allow us to leverage the devicemanager code and get rid of our own `pkg/server` package.

### CODE REVIEW

**Comment by ffromani** [comment]
let's wait for e2e test enablement in CI before to merge this PR

**Review by swatisehgal — APPROVED** [review]
> let's wait for e2e test enablement in CI before to merge this PR

/hold
feel free to unhold once the e2e-test enablement PR is merged.

/lgtm

**Comment by ffromani** [comment]
e2e lane passed, so merging (as agreed in https://github.com/k8stopologyawareschedwg/sample-device-plugin/pull/9#pullrequestreview-1099838913 )

**Comment by ffromani** [comment]
image

**Pull request merged**
