### PR TITLE
manifests: add support for kustomization

### PR DESCRIPTION
**Pull request by Tal-or**
Use kustomize in order to deploy sample-device-plugin.
This will allow an easier deployment (all in one keystroke) and more flexible device configuration which is going to be added in a following commit.
We left the old configuration for now, but it can be removed if we decide that we're happy with this change.

### CODE REVIEW

**Review by swatisehgal — COMMENTED** [review]
Looking good. This will certainly simplify the deployment process. Great to see a `default` overlay that deploys all the device plugins. In addition to this, we should add overlays corresponding to the individual device plugins in case we want to deploy a subset of these device plugins. This would provide more flexibility while deploying these device plugins allowing us to do something like below for deployment of deviceplugin A and B: 
```
kubectl apply -k deployment/overlays/devicepluginA
kubectl apply -k deployment/overlays/devicepluginB
```

**Comment by swatisehgal** [comment]
We cannot inherit files that are not present in or below the overlay. I am getting the following error:

```
$ kubectl apply -k deployment/overlays/default
error: loading KV pairs: file sources: [../devicepluginA/example_com_deviceA.yaml]: security; file '/home/swsehgal/go/src/github.com/k8stopologyawareschedwg/sample-device-plugin/deployment/overlays/devicepluginA/example_com_deviceA.yaml' is not in or below '/home/swsehgal/go/src/github.com/k8stopologyawareschedwg/sample-device-plugin/deployment/overlays/default'
```
I guess the best way to overcome this is to provide the configs files within the overlay itself. I believe it is a reasonable approach given that a specific overlay leads to a specific deployment  .

We also need to provide the specific base directories explicitly in case of default overlay:
```

 resources:
-  - ../../base
+- ../../base/devicepluginA-ds
+- ../../base/devicepluginB-ds
+- ../../base/devicepluginC-ds
 
 configMapGenerator:
   - name: device-a-configmap
     files:
-      - ../devicepluginA/example_com_deviceA.yaml
+      - example_com_deviceA.yaml
   - name: device-b-configmap
     files:
-      - ../devicepluginB/example_com_deviceB.yaml
+      - example_com_deviceB.yaml
   - name: device-c-configmap
     files:
-      - ../devicepluginC/example_com_deviceC.yaml
+      - example_com_deviceC.yaml
```

**Comment by Tal-or** [comment]
@swatisehgal let's merge the current PR and create a separate one for could-infra-vendor-specific environments

**Review by swatisehgal — APPROVED** [review]
/lgtm

Given that this works on a kind based cluster, lets merged this.

Will submit a follow-up PR for deployment on OCP cluster.

**Pull request merged**
